# These are supported funding model platforms

github: byAd12
patreon: byAd12
ko_fi: byad12
custom: ['https://www.paypal.com/paypalme/byAd112', 'https://www.paypal.com/donate/?hosted_button_id=9D8YV9UW5LYKQ']
